# Generated by Django 6.0.7 on 2026-07-25 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cognito_sub', models.CharField(db_index=True, max_length=64, unique=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'app_users',
            },
        ),
        migrations.CreateModel(
            name='PositionLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_qty', models.DecimalField(decimal_places=6, max_digits=18)),
                ('remaining_qty', models.DecimalField(decimal_places=6, max_digits=18)),
                ('open_price', models.DecimalField(decimal_places=4, max_digits=14)),
                ('opened_at', models.DateTimeField(db_index=True)),
                ('closed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('close_price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('realized_pnl', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('hold_days', models.IntegerField(blank=True, null=True)),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='market.security')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='trading.appuser')),
            ],
            options={
                'db_table': 'position_lots',
                'ordering': ['user', 'security', 'opened_at'],
            },
        ),
        migrations.CreateModel(
            name='TradeFill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=4)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=18)),
                ('price', models.DecimalField(decimal_places=4, max_digits=14)),
                ('filled_at', models.DateTimeField(db_index=True)),
                ('source_event_id', models.CharField(max_length=128, unique=True)),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fills', to='trading.positionlot')),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fills', to='market.security')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fills', to='trading.appuser')),
            ],
            options={
                'db_table': 'trade_fills',
                'ordering': ['user', 'security', 'filled_at'],
            },
        ),
        migrations.AddIndex(
            model_name='positionlot',
            index=models.Index(condition=models.Q(('closed_at__isnull', False)), fields=['user', 'closed_at'], name='idx_lot_user_closed'),
        ),
        migrations.AddIndex(
            model_name='positionlot',
            index=models.Index(condition=models.Q(('closed_at__isnull', True)), fields=['user', 'security', 'opened_at'], name='idx_lot_open_fifo'),
        ),
        migrations.AddConstraint(
            model_name='positionlot',
            constraint=models.CheckConstraint(condition=models.Q(('remaining_qty__gte', 0)), name='lot_remaining_qty_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='positionlot',
            constraint=models.CheckConstraint(condition=models.Q(('remaining_qty__lte', models.F('original_qty'))), name='lot_remaining_lte_original'),
        ),
        migrations.AddIndex(
            model_name='tradefill',
            index=models.Index(fields=['user', 'security', 'filled_at'], name='idx_fill_user_sec_time'),
        ),
        migrations.AddIndex(
            model_name='tradefill',
            index=models.Index(condition=models.Q(('lot__isnull', True)), fields=['lot'], name='idx_fill_unmatched'),
        ),
        migrations.AddConstraint(
            model_name='tradefill',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='fill_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='tradefill',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='fill_price_non_negative'),
        ),
    ]
