# Generated by Django 6.0.7 on 2026-07-25 02:45

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, help_text='Ticker as used by the data provider, e.g. AAPL', max_length=12, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('asset_type', models.CharField(choices=[('stock', 'Stock'), ('etf', 'ETF'), ('index', 'Index')], default='stock', max_length=8)),
                ('sector', models.CharField(blank=True, db_index=True, max_length=64)),
                ('exchange', models.CharField(blank=True, max_length=32)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('first_bar_date', models.DateField(blank=True, null=True)),
                ('last_bar_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'securities',
                'db_table': 'securities',
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='DailyBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bar_date', models.DateField()),
                ('open', models.DecimalField(decimal_places=4, max_digits=14)),
                ('high', models.DecimalField(decimal_places=4, max_digits=14)),
                ('low', models.DecimalField(decimal_places=4, max_digits=14)),
                ('close', models.DecimalField(decimal_places=4, max_digits=14)),
                ('adj_close', models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('volume', models.BigIntegerField()),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bars', to='market.security')),
            ],
            options={
                'db_table': 'daily_bars',
                'ordering': ['security', '-bar_date'],
                'get_latest_by': 'bar_date',
                'indexes': [models.Index(fields=['security', '-bar_date'], name='idx_bar_security_date_desc'), models.Index(fields=['bar_date'], name='idx_bar_date')],
                'constraints': [models.UniqueConstraint(fields=('security', 'bar_date'), name='uniq_daily_bar_security_date'), models.CheckConstraint(condition=models.Q(('high__gte', models.F('low'))), name='daily_bar_high_gte_low')],
            },
        ),
    ]
