# Generated by Django 6.0.7 on 2026-07-25 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_type', models.CharField(choices=[('risk', 'Portfolio risk'), ('behavior', 'Trading behaviour')], max_length=16)),
                ('as_of', models.DateField()),
                ('lookback_days', models.IntegerField(default=756)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('error_message', models.TextField(blank=True)),
                ('securities_included', models.JSONField(blank=True, default=list)),
                ('securities_excluded', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='trading.appuser')),
            ],
            options={
                'db_table': 'analysis_runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BehaviorMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_hold_days_winners', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('avg_hold_days_losers', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('disposition_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('total_closed_lots', models.IntegerField(default=0)),
                ('winning_lots', models.IntegerField(default=0)),
                ('win_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('avg_win_pct', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('avg_loss_pct', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('payoff_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('total_fills', models.IntegerField(default=0)),
                ('trades_per_month', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('turnover_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('realized_return', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('buy_hold_return', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('vs_buy_hold', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('distributions', models.JSONField(blank=True, default=dict)),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_metrics', to='analytics.analysisrun')),
            ],
            options={
                'verbose_name_plural': 'behavior metrics',
                'db_table': 'behavior_metrics',
            },
        ),
        migrations.CreateModel(
            name='RiskMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_vol', models.DecimalField(decimal_places=6, max_digits=12)),
                ('benchmark_vol', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('beta', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('var_95', models.DecimalField(decimal_places=6, max_digits=12)),
                ('expected_shortfall_95', models.DecimalField(decimal_places=6, max_digits=12)),
                ('max_drawdown', models.DecimalField(decimal_places=6, max_digits=12)),
                ('max_drawdown_start', models.DateField(blank=True, null=True)),
                ('max_drawdown_end', models.DateField(blank=True, null=True)),
                ('hhi', models.DecimalField(decimal_places=6, max_digits=10)),
                ('effective_holdings', models.DecimalField(decimal_places=4, max_digits=10)),
                ('avg_correlation', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('annualised_return', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('sharpe_ratio', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('correlation_matrix', models.JSONField(default=dict)),
                ('risk_contributions', models.JSONField(default=dict)),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_metrics', to='analytics.analysisrun')),
            ],
            options={
                'verbose_name_plural': 'risk metrics',
                'db_table': 'risk_metrics',
            },
        ),
        migrations.AddIndex(
            model_name='analysisrun',
            index=models.Index(condition=models.Q(('status', 'succeeded')), fields=['user', 'run_type', '-as_of'], name='idx_run_cache_lookup'),
        ),
    ]
